
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployemnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicure
      env: prod
  template:
    metadata:
      labels:
        app: medicure
        env: prod
    spec:
      containers:
      - name: medicure
        image: atul0074/medicure:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: medicure
    env: prod
  ports:
  - port: 80
    targetPort: 8080
